export const constants = {
  DEFAULT_LANGUAGE: 'en',
  PAGE_TITLE_PREFIX: 'Business App',
  LOGIN_SUCCESS_REDIRECT_URL: '/dashbored',
  MIN_LENGTH_TEXT_INPUT: 8,
  MAX_LENGTH_TEXT_INPUT: 191,
  MAX_LENGTH_TEXTAREA: 16777215,
  TABLE_ROWS_LENGTH: 10,
  MAX_FILE_SIZE: 10_485_760,
  DATA_LIMIT: 12,
  DEFAULT_COUNTRY_ID: 110,
  DATE_FORMAT: 'YYYY-MM-DD HH:mm',
};
